nodes:
  - id: pi_node_1
    ip: 192.168.2.106
    dashboard_port: 8001
  - id: pi_node_2
    ip: 192.168.2.107
    dashboard_port: 8002
  - id: pi_node_3
    ip: 192.168.2.104
    dashboard_port: 8003
  - id: pi_node_4
    ip: 192.168.2.102
    dashboard_port: 8004
  - id: pi_node_5
    ip: 192.168.2.105
    dashboard_port: 8005

mqtt:
  host: 192.168.2.11
  port: 1883
  username: broker1
  password: broker1pass

topics:
  metrics: iot/metrics
  transactions: iot/transactions

defaults:
  qos: 1

